import { BLUE_STYLE, CYAN_STYLE, PURPLE_STYLE, RED_STYLE } from "./schemas";

export const examplePlateCsv = `
idx,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48
A,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
B,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
C,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
D,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
E,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
F,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
G,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
H,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
I,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
J,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
K,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
L,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
M,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
N,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
O,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
P,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
Q,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
R,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
S,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
T,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
U,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
V,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
W,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
X,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
Y,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
Z,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
AA,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
AB,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
AC,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
AD,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
AE,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
AF,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control,Treatment 1,Treatment 2,Positive Control,Negative Control
`;

export const exampleRowAnnotations = [
  {
    rows: [0, 1, 2, 9, 10, 11, 18, 19, 20, 27, 28, 29, 36, 37, 38, 45, 46, 47],
    label: "Antibody 1 μmol/L",
    id: "Antibody 1 μmol/L",
    annotationStyle: CYAN_STYLE,
  },
  {
    rows: [3, 4, 5, 12, 13, 14, 21, 22, 23, 30, 31, 32, 39, 40, 41, 48, 49, 50],
    label: "Antibody 2 μmol/L",
    id: "Row Annotation 1",
    annotationStyle: PURPLE_STYLE,
  },
  {
    rows: [6, 7, 8, 15, 16, 17, 24, 25, 26, 33, 34, 35, 42, 43, 44, 51, 52, 53],
    label: "Antibody 3 μmol/L",
    id: "Row Annotation 2",
    annotationStyle: RED_STYLE,
  },
];

export const exampleColAnnotations = [
  {
    cols: [0, 1, 2, 3, 12, 13, 14, 15, 24, 25, 26, 27, 36, 37, 38, 39],
    label: "Patient 1",
    id: "Patient 1",
    annotationStyle: CYAN_STYLE,
  },
  {
    cols: [4, 5, 6, 7, 16, 17, 18, 19, 28, 29, 30, 31, 40, 41, 42, 43],
    label: "Patient 2",
    id: "Patient 2",
    annotationStyle: PURPLE_STYLE,
  },
  {
    cols: [8, 9, 10, 11, 20, 21, 22, 23, 32, 33, 34, 35, 44, 45, 46, 47],
    label: "Patient 3",
    id: "Patient 3",
    annotationStyle: BLUE_STYLE,
  },
];
